# Generated by Django 5.1.4 on 2024-12-08 11:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='awards/images/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Mukofot',
                'verbose_name_plural': 'Mukofotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('url', models.URLField(verbose_name='URL manzil')),
                ('is_required', models.BooleanField(default=True, verbose_name='Majburiy obuna')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kanal',
                'verbose_name_plural': 'Kanallar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('total_users', models.IntegerField(default=0, verbose_name='Jami foydalanuvchilar')),
                ('active_users', models.IntegerField(default=0, verbose_name='Faol foydalanuvchilar')),
                ('total_subscriptions', models.IntegerField(default=0, verbose_name='Jami obunalar')),
                ('total_score', models.IntegerField(default=0, verbose_name='Jami ballar')),
                ('referral_counts', models.IntegerField(default=0, verbose_name='Referal hisoblanganlar')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ballar')),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Referal kod')),
                ('is_referral_counted', models.BooleanField(default=False, verbose_name='Referal ball berilganmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='konkurs.user', verbose_name='Kim tomonidan taklif qilingan')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Obuna holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konkurs.link', verbose_name='Kanal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konkurs.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'unique_together': {('user', 'channel')},
            },
        ),
        migrations.AddField(
            model_name='link',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_channels', through='konkurs.UserSubscription', to='konkurs.user', verbose_name="Obuna bo'lganlar"),
        ),
    ]
